ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of hahm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_43 = ', GC_43
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_46 = ', GC_46
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_73 = ', GC_73
      WRITE(*,2) 'GC_74 = ', GC_74
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_86 = ', GC_86
