ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_2 = -(MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_3 = (2.000000D+00*MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_4 = -(MDL_EE*MDL_COMPLEXI)
      GC_34 = -(MDL_CA*MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00
     $ *MDL_SW)
      GC_35 = (MDL_CA*MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_36 = -(MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_SA)/(2.000000D+00
     $ *MDL_SW)
      GC_37 = (MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_SA)/(2.000000D+00*MDL_SW)
      GC_42 = (MDL_EE*MDL_ETA*MDL_COMPLEXI*MDL_SA)/(6.000000D+00
     $ *MDL_CW)-(MDL_CA*MDL_EE*MDL_COMPLEXI*MDL_SW)/(6.000000D+00
     $ *MDL_CW)
      GC_43 = -(MDL_EE*MDL_ETA*MDL_COMPLEXI*MDL_SA)/(2.000000D+00
     $ *MDL_CW)+(MDL_CA*MDL_EE*MDL_COMPLEXI*MDL_SW)/(2.000000D+00
     $ *MDL_CW)
      GC_45 = (MDL_CA*MDL_EE*MDL_ETA*MDL_COMPLEXI)/(6.000000D+00
     $ *MDL_CW)+(MDL_EE*MDL_COMPLEXI*MDL_SA*MDL_SW)/(6.000000D+00
     $ *MDL_CW)
      GC_46 = -(MDL_CA*MDL_EE*MDL_ETA*MDL_COMPLEXI)/(2.000000D+00
     $ *MDL_CW)-(MDL_EE*MDL_COMPLEXI*MDL_SA*MDL_SW)/(2.000000D+00
     $ *MDL_CW)
      GC_71 = -((MDL_CH*MDL_COMPLEXI*MDL_YC)/MDL_SQRT__2)
      GC_72 = -((MDL_COMPLEXI*MDL_SH*MDL_YC)/MDL_SQRT__2)
      GC_73 = -((MDL_CH*MDL_COMPLEXI*MDL_YD)/MDL_SQRT__2)
      GC_74 = -((MDL_COMPLEXI*MDL_SH*MDL_YD)/MDL_SQRT__2)
      GC_75 = -((MDL_CH*MDL_COMPLEXI*MDL_YE)/MDL_SQRT__2)
      GC_76 = -((MDL_COMPLEXI*MDL_SH*MDL_YE)/MDL_SQRT__2)
      GC_77 = -((MDL_CH*MDL_COMPLEXI*MDL_YM)/MDL_SQRT__2)
      GC_78 = -((MDL_COMPLEXI*MDL_SH*MDL_YM)/MDL_SQRT__2)
      GC_79 = -((MDL_CH*MDL_COMPLEXI*MDL_YS)/MDL_SQRT__2)
      GC_80 = -((MDL_COMPLEXI*MDL_SH*MDL_YS)/MDL_SQRT__2)
      GC_85 = -((MDL_CH*MDL_COMPLEXI*MDL_YU)/MDL_SQRT__2)
      GC_86 = -((MDL_COMPLEXI*MDL_SH*MDL_YU)/MDL_SQRT__2)
      END
