ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MT,MDL_MU,MDL_MW,MDL_MM,MDL_MZ,MDL_MH
     $ ,MDL_MHS,MDL_MZP,MDL_MB,MDL_MC,MDL_MTA,MDL_MS,MDL_ME,MDL_MD

      COMMON/MASSES/ MDL_MT,MDL_MU,MDL_MW,MDL_MM,MDL_MZ,MDL_MH,MDL_MHS
     $ ,MDL_MZP,MDL_MB,MDL_MC,MDL_MTA,MDL_MS,MDL_ME,MDL_MD


      DOUBLE PRECISION MDL_WH,MDL_WZP,MDL_WZ,MDL_WHS,MDL_WT,MDL_WW

      COMMON/WIDTHS/ MDL_WH,MDL_WZP,MDL_WZ,MDL_WHS,MDL_WT,MDL_WW


      DOUBLE COMPLEX GC_8, GC_18, GC_2, GC_3, GC_4, GC_34, GC_35,
     $  GC_36, GC_37, GC_42, GC_43, GC_45, GC_46, GC_71, GC_72, GC_73,
     $  GC_74, GC_75, GC_76, GC_77, GC_78, GC_79, GC_80, GC_85, GC_86

      COMMON/COUPLINGS/ GC_8, GC_18, GC_2, GC_3, GC_4, GC_34, GC_35,
     $  GC_36, GC_37, GC_42, GC_43, GC_45, GC_46, GC_71, GC_72, GC_73,
     $  GC_74, GC_75, GC_76, GC_77, GC_78, GC_79, GC_80, GC_85, GC_86

