ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MW,MDL_MH,MDL_MTA,MDL_MZ,MDL_MT,MDL_MB

      COMMON/MASSES/ MDL_MW,MDL_MH,MDL_MTA,MDL_MZ,MDL_MT,MDL_MB


      DOUBLE PRECISION MDL_WW,MDL_WH,MDL_WZ,MDL_WT

      COMMON/WIDTHS/ MDL_WW,MDL_WH,MDL_WZ,MDL_WT


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_50, GC_58, GC_59

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_50, GC_58, GC_59

